### ISSUE TITLE
links to "HCL Design System" lead to 404

### ISSUE THREAD

**Issue by MagnaFrisia90** [HCL-TECH-SOFTWARE/connections-ui-docs#14]
![grafik](https://github.com/HCL-TECH-SOFTWARE/connections-ui-docs/assets/115451939/a518837c-6202-40d0-bdb9-f09e32824c9c)

**Comment by caiaga** [comment]
Hello @MagnaFrisia90, the link points to https://github.com/HCL-TECH-SOFTWARE/connections-ui-docs/blob/master/internal-link-redacted which was purposefully redacted as it points to an internal system (as the same documentation is used for our developers internally). I understand that this causes confusion and we had similar issues raised before. We are currently overhauling this approach to improve the understandability by external readers.
