### ISSUE TITLE
com.hcl.connections.nav vs. payload.match ?

### ISSUE THREAD

**Issue by umeli** [HCL-TECH-SOFTWARE/connections-ui-docs#3]
Does the com.hcl.connections.nav support the payload.match tags ?

![image](https://user-images.githubusercontent.com/710539/221872228-b525a477-e6d2-4096-ac54-dd1b1167720c.png)

Adding a different menu based on the matcher doesn't seem to work for this extension. Is there any other way to achieve this or how can we hide these customizations from externals ?

**Comment by david-bell-hcl** [comment]
@umeli @caiaga - unfortunately it does not - the match capability is in customizer (mw-proxy) not appregistry itself. Stefan and I have talked about pushing that into appregistry to make it a more generally applicable feature that could be used by any app consuming appregistry payloads.  However you can achieve what you need using this; external is not really a role but the navbar can use this to hide things: "forbiddenRoles": ["external"]
